data:
  dataset_root: 
  data_save_path: 
  save_dir: 
  preprocessed: false
  fold_id: 0
  cfd_mesh: true
  r: null
  use_height: false
  
model:
  n_block: 8
  n_mode: 512
  n_dim: 512
  n_head: 8
  n_layer: 2
  attn: Attention_Vanilla
  act: GELU
  y1_dim: 7
  y2_dim: 4

training:
  exp_name: ShapNetCar/run0
  seed: 42
  num_epochs: 100
  batch_size: 1
  save_freq: 5
  model_path: "model.pth"
  
  optimizer:
    name: Adam
    params:
      lr: 1.0e-4
  
  scheduler:
    name: CosineAnnealingLR
    params:
      T_max: 100
      eta_min: 1.0e-6

exp_name: ShapNetCar/run0