data:
  dataset_root: 
  data_save_path: 
  sample_cache_dir: 
  cache_dir: 
  split_interval: 5
  seq_length: 5
  
model:
  n_block: 4
  n_mode: 128
  n_dim: 128
  n_head: 8
  n_layer: 2
  attn: Attention_Vanilla
  act: GELU
  y1_dim: 13
  y2_dim: 2

training:
  exp_name: Cylinder/run0
  seed: 42
  num_epochs: 100
  batch_size: 2
  save_freq: 5
  model_path: "model.pth"
  
  optimizer:
    name: Adam
    params:
      lr: 1.0e-4
  
  scheduler:
    name: CosineAnnealingLR
    params:
      T_max: 100
      eta_min: 1.0e-6

exp_name: Cylinder/run0
