data:
  dataset_root: 
  data_save_path: 
  sample_cache_dir: 
  cache_dir: 
  split_interval: 5
  seq_length: 5
  
model:
  trunk_size: 13
  horiz_fourier_dim: 0
  output_size: 2
  space_dim: 2
  attn_type: linear
  ffn_dropout: 0.0
  attn_dropout: 0.0
  n_hidden: 64
  n_head: 8
  n_layers: 2
  act: gelu
  n_experts: 1
  n_inner: 2
  mlp_layers: 1

training:
  exp_name: Cylinder/run0
  seed: 42
  num_epochs: 100
  batch_size: 1
  save_freq: 5
  model_path: "model.pth"
  
  optimizer:
    name: Adam
    params:
      lr: 1.0e-4
  
  scheduler:
    name: CosineAnnealingLR
    params:
      T_max: 100
      eta_min: 1.0e-6

exp_name: Cylinder/run0